# Generated by Django 2.0.7 on 2018-08-13 03:50

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='活动名称')),
                ('img', models.ImageField(upload_to='upload/activity/%Y/')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 13, 3, 50, 42, 742998, tzinfo=utc), verbose_name='发布时间')),
                ('begin_date', models.DateTimeField(blank=True, default=None, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, default=None, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 50, 42, 740611, tzinfo=utc), editable=False, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 50, 42, 740657, tzinfo=utc), editable=False, verbose_name='修改时间')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sequence', models.IntegerField(blank=True, null=True, unique=True, verbose_name='排列顺序')),
                ('batch_code', models.UUIDField(default=uuid.UUID('6c98a16a-06a8-4b01-9396-10411e84320d'), editable=False, unique=True, verbose_name='批次编号')),
                ('count', models.IntegerField(verbose_name='生成数量')),
                ('is_gen', models.BooleanField(default=True, editable=False, verbose_name='已经生成？')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'ordering': ['-last_mod_time'],
            },
        ),
        migrations.CreateModel(
            name='TEst1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='活动名称')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 50, 42, 740611, tzinfo=utc), editable=False, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=datetime.datetime(2018, 8, 13, 3, 50, 42, 740657, tzinfo=utc), editable=False, verbose_name='修改时间')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sequence', models.IntegerField(blank=True, null=True, unique=True, verbose_name='排列顺序')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', ckeditor.fields.RichTextField(max_length=500, verbose_name='产品介绍')),
                ('feature', ckeditor.fields.RichTextField(max_length=500, verbose_name='产品特点')),
                ('chateau_name', models.CharField(max_length=50, verbose_name='酒庄名称')),
                ('chateau', models.ImageField(upload_to='upload/wine/chateau/%Y/%m/', verbose_name='酒庄介绍')),
                ('area_name', models.CharField(max_length=50, verbose_name='产区名称')),
                ('area', models.ImageField(upload_to='upload/wine/area/%Y/%m/', verbose_name='产区介绍')),
                ('sober_up_time_best', models.IntegerField(verbose_name='最佳醒酒时间')),
                ('sober_up_time1', models.IntegerField(verbose_name='醒酒时间1')),
                ('sober_up_taste1', models.TextField(max_length=50, verbose_name='口感1')),
                ('sober_up_time2', models.IntegerField(verbose_name='醒酒时间2')),
                ('sober_up_taste2', models.TextField(max_length=50, verbose_name='口感2')),
                ('sober_up_time3', models.IntegerField(verbose_name='醒酒时间3')),
                ('sober_up_taste3', models.TextField(max_length=50, verbose_name='口感3')),
                ('sober_up_time_worst', models.IntegerField(verbose_name='不易超过醒酒时间')),
                ('storage_mode', models.TextField(max_length=30, verbose_name='存放方式')),
            ],
            options={
                'verbose_name': '红酒',
                'verbose_name_plural': '红酒',
                'ordering': ['-last_mod_time'],
            },
        ),
        migrations.CreateModel(
            name='WineItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='主键')),
                ('wine_code', models.CharField(default=None, editable=False, max_length=12, unique=True, verbose_name='核销编码')),
                ('security_code', models.CharField(max_length=10, verbose_name='验证码')),
                ('status', models.CharField(choices=[('w', '未核销'), ('y', '已核销')], default='w', max_length=1, verbose_name='核销状态')),
                ('count', models.IntegerField(default=0, verbose_name='第几次访问？')),
                ('created_time', models.DateTimeField(editable=False, verbose_name='创建时间')),
                ('first_visit_time', models.DateTimeField(editable=False, null=True, verbose_name='第一次访问时间')),
                ('last_visit_time', models.DateTimeField(editable=False, null=True, verbose_name='最后访问时间')),
                ('url', models.URLField(default=None, verbose_name='二维码地址')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Batch')),
            ],
            options={
                'verbose_name': '核销',
                'verbose_name_plural': '核销',
                'ordering': ['-last_visit_time'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Wine'),
        ),
    ]
