# Generated by Django 2.0.7 on 2018-08-16 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='certificate',
            field=models.ImageField(default=None, null=True, upload_to='upload/wine/cert/%y/%m/', verbose_name='原产地证'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 4, 10, 3, 121753, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.UUIDField(default=uuid.UUID('e70d5851-dfca-44bf-a620-fbe294ac7113'), editable=False, unique=True, verbose_name='批次编号'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 10, 3, 119006, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 10, 3, 119055, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 10, 3, 119006, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 10, 3, 119055, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='batch',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.Batch'),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='count',
            field=models.IntegerField(default=0, editable=False, verbose_name='第几次访问？'),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='security_code',
            field=models.CharField(editable=False, max_length=10, verbose_name='验证码'),
        ),
    ]
