# Generated by Django 2.0.7 on 2018-08-16 04:13

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180816_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 4, 13, 6, 282344, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.UUIDField(default=uuid.UUID('daf95157-3d65-42eb-bfc7-979b4edfa30f'), editable=False, unique=True, verbose_name='批次编号'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 13, 6, 279461, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 13, 6, 279509, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 13, 6, 279461, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='element',
            field=ckeditor.fields.RichTextField(default=None, max_length=50, null=True, verbose_name='成分'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 13, 6, 279509, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
    ]
