# Generated by Django 2.0.7 on 2018-08-16 04:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180816_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='agent_com',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='进口代理商'),
        ),
        migrations.AddField(
            model_name='batch',
            name='analyze_book',
            field=models.ImageField(default=None, null=True, upload_to='upload/batch/analyze/%y/%m/', verbose_name='成分分析证书'),
        ),
        migrations.AddField(
            model_name='batch',
            name='bill_code',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='报关单号'),
        ),
        migrations.AddField(
            model_name='batch',
            name='bill_com',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='报关企业'),
        ),
        migrations.AddField(
            model_name='batch',
            name='bill_img',
            field=models.ImageField(default=None, null=True, upload_to='upload/batch/bill/%y/%m/', verbose_name='通关单'),
        ),
        migrations.AddField(
            model_name='batch',
            name='bill_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='报关时间'),
        ),
        migrations.AddField(
            model_name='batch',
            name='check_code',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='商检单号'),
        ),
        migrations.AddField(
            model_name='batch',
            name='check_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='检测日期'),
        ),
        migrations.AddField(
            model_name='batch',
            name='check_prove',
            field=models.ImageField(default=None, null=True, upload_to='upload/batch/checkprove/%y/%m/', verbose_name='检验检疫证明'),
        ),
        migrations.AddField(
            model_name='batch',
            name='inspection_com',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='报检企业'),
        ),
        migrations.AddField(
            model_name='batch',
            name='promise_book',
            field=models.ImageField(default=None, null=True, upload_to='upload/batch/promise/%y/%m/', verbose_name='企业承诺书'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 4, 27, 45, 328559, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.UUIDField(default=uuid.UUID('86e74da2-1931-452e-b187-c26a68410b75'), editable=False, unique=True, verbose_name='批次编号'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 27, 45, 323891, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 27, 45, 323945, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 27, 45, 323891, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 4, 27, 45, 323945, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
    ]
