# Generated by Django 2.0.7 on 2018-08-16 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180816_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='upload/home/banner/%y/%m/', verbose_name='轮播图')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 6, 25, 56, 8507, tzinfo=utc), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.UUIDField(default=uuid.UUID('ecb6fa25-5971-4dee-911c-aefff1052ee2'), editable=False, unique=True, verbose_name='批次编号'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 6, 25, 56, 2936, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 6, 25, 56, 2996, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 6, 25, 56, 2936, tzinfo=utc), editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 6, 25, 56, 2996, tzinfo=utc), editable=False, verbose_name='修改时间'),
        ),
    ]
